from pydantic import AliasChoices, BaseModel, EmailStr, field_validator, HttpUrl, model_validator, Field
from typing import List, Optional, Dict, Any, Union
from datetime import datetime
from ..models import Priority, Status, TestStatus, ResultStatus, Role, Permission, CustomFieldType, TestType, RecycleBinType, RequirementStatus, DefectStatus, DefectSeverity, DefectPriority, DefectLinkType, MilestoneStatus, NotificationType, StepCategory, StepComplexity, DocStatus
import re
import html

from .versioning import (
    DateValidationRules,
    NumberValidationRules,
    SelectValidationRules,
    TestCaseVersionBase,
    TestCaseVersionCreate,
    TestCaseVersionUpdate,
    TextValidationRules,
    VersionComparisonBase,
    VersionComparisonCreate,
    VersionLockBase,
    VersionLockCreate,
    VersionTagBase,
    VersionTagCreate,
)
from ..services.webhook_security import normalize_webhook_url

from .core import *
from .custom_fields import *
from .integrations_settings import *
from .requirements import *

def _sanitize_defect_strings(data):
    """Idempotently escape HTML in user-supplied string fields.

    Skips URL/identifier fields where escaping would mangle valid input
    (e.g. query strings containing ``&``).
    """
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, str) and key not in _DEFECT_SANITIZE_SKIP:
                # Unescape before escaping so re-saving an already-stored value
                # is idempotent — a bare ``html.escape`` would compound
                # ``&lt;`` into ``&amp;lt;`` on every update.
                data[key] = html.escape(html.unescape(value))
    return data


def _validate_optional_http_url(value: Optional[str]) -> Optional[str]:
    if value is None:
        return value
    cleaned = value.strip()
    if not cleaned:
        return None
    if not re.fullmatch(r"https?://\S+", cleaned, flags=re.IGNORECASE):
        raise ValueError("External issue URL must be a valid http or https URL")
    return cleaned


class DefectBase(BaseModel):
    title: str = Field(max_length=255)
    description: Optional[str] = None
    # Server-derived from the project sequence (P{pid}-DEF-NNN); optional on input.
    defect_id: Optional[str] = Field(default=None, max_length=50)
    status: DefectStatus = DefectStatus.OPEN
    severity: DefectSeverity = DefectSeverity.MEDIUM
    priority: DefectPriority = DefectPriority.MEDIUM
    test_case_id: Optional[int] = None
    test_run_id: Optional[int] = None
    requirement_id: Optional[int] = None
    assigned_to: Optional[int] = None
    tags: Optional[str] = Field(default=None, max_length=500)
    steps_to_reproduce: Optional[str] = None
    expected_result: Optional[str] = None
    actual_result: Optional[str] = None
    environment: Optional[str] = Field(default=None, max_length=255)
    browser_info: Optional[str] = Field(default=None, max_length=255)
    attachments: Optional[str] = None
    estimated_fix_time: Optional[float] = None
    actual_fix_time: Optional[float] = None
    external_issue_id: Optional[str] = Field(default=None, max_length=100)
    external_issue_url: Optional[str] = Field(default=None, max_length=500)
    external_sync_status: Optional[str] = Field(default=None, max_length=50)

    @model_validator(mode='before')
    @classmethod
    def sanitize_html(cls, data):
        return _sanitize_defect_strings(data)

    @field_validator('external_issue_url')
    @classmethod
    def validate_external_issue_url(cls, value):
        return _validate_optional_http_url(value)


class DefectCreate(DefectBase):
    project_id: int = Field(ge=1)
    reported_by: Optional[int] = None

    @model_validator(mode='after')
    def reject_client_defect_id(self):
        if self.defect_id:
            raise ValueError("Defect ID is generated by the server")
        return self


class DefectUpdate(BaseModel):
    defect_id: Optional[str] = Field(default=None, max_length=50)
    title: Optional[str] = Field(default=None, max_length=255)
    description: Optional[str] = None
    status: Optional[DefectStatus] = None
    severity: Optional[DefectSeverity] = None
    priority: Optional[DefectPriority] = None
    test_case_id: Optional[int] = None
    test_run_id: Optional[int] = None
    requirement_id: Optional[int] = None
    assigned_to: Optional[int] = None
    tags: Optional[str] = Field(default=None, max_length=500)
    steps_to_reproduce: Optional[str] = None
    expected_result: Optional[str] = None
    actual_result: Optional[str] = None
    environment: Optional[str] = Field(default=None, max_length=255)
    browser_info: Optional[str] = Field(default=None, max_length=255)
    attachments: Optional[str] = None
    estimated_fix_time: Optional[float] = None
    actual_fix_time: Optional[float] = None
    external_issue_id: Optional[str] = Field(default=None, max_length=100)
    external_issue_url: Optional[str] = Field(default=None, max_length=500)
    external_sync_status: Optional[str] = Field(default=None, max_length=50)

    @model_validator(mode='before')
    @classmethod
    def sanitize_html(cls, data):
        return _sanitize_defect_strings(data)

    @field_validator('external_issue_url')
    @classmethod
    def validate_external_issue_url(cls, value):
        return _validate_optional_http_url(value)


class Defect(DefectBase):
    id: int
    project_seq: Optional[int] = None  # per-project sequence (URLs/badges)
    project_id: int
    reported_by: int
    external_last_sync: Optional[datetime] = None
    resolution: Optional[str] = None
    root_cause: Optional[str] = None
    fix_version: Optional[str] = None
    found_in_version: Optional[str] = None
    duplicate_of: Optional[int] = None
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# Test Result <-> Defect link schemas
class DefectSummary(BaseModel):
    """Lightweight defect representation for embedding in link responses."""
    id: int
    defect_id: str
    title: str
    status: DefectStatus
    severity: DefectSeverity
    priority: DefectPriority
    assigned_to: Optional[int] = None
    external_issue_url: Optional[str] = None

    class Config:
        from_attributes = True
        use_enum_values = True


class TestResultFailingStepSnapshot(BaseModel):
    """User-selected failed/blocked step context to attach to the immutable link snapshot."""
    step_id: Optional[int] = Field(None, ge=1)
    step_number: Optional[int] = Field(None, ge=1)
    status: Optional[str] = Field(None, max_length=20)
    actual_result: Optional[str] = Field(None, max_length=5000)
    notes: Optional[str] = Field(None, max_length=5000)

    @model_validator(mode='after')
    def require_step_reference(self):
        if self.step_id is None and self.step_number is None:
            raise ValueError("Provide either step_id or step_number")
        if self.status:
            normalized_status = self.status.strip().lower()
            if normalized_status not in {"failed", "fail", "blocked", "block"}:
                raise ValueError("Failing step status must be failed or blocked")
            self.status = normalized_status
        return self


class TestResultDefectLinkCreate(BaseModel):
    """Link a defect to a test result. Provide either an existing defect_id
    or a new_defect payload to create and link in one call."""
    defect_id: Optional[int] = None
    link_type: DefectLinkType = DefectLinkType.FOUND
    new_defect: Optional[DefectCreate] = None
    failing_step: Optional[TestResultFailingStepSnapshot] = None

    @model_validator(mode='after')
    def require_one_target(self):
        if self.defect_id is None and self.new_defect is None:
            raise ValueError("Provide either defect_id or new_defect")
        if self.defect_id is not None and self.new_defect is not None:
            raise ValueError("Provide only one of defect_id or new_defect")
        return self


class TestResultDefectLinkSnapshotUpdate(BaseModel):
    """Explicit correction payload for a stored result/step snapshot."""
    failing_step: Optional[TestResultFailingStepSnapshot] = None
    clear_failing_step: bool = False


class TestResultDefectLink(BaseModel):
    id: int
    test_result_id: int
    defect_id: int
    link_type: str
    result_snapshot: Optional[dict] = None
    failing_step_snapshot: Optional[dict] = None
    snapshot_created_at: Optional[datetime] = None
    created_by: Optional[int] = None
    created_at: datetime
    defect: Optional[DefectSummary] = None

    class Config:
        from_attributes = True


class DefectUserSummary(BaseModel):
    id: int
    username: str
    email: Optional[str] = None
    full_name: Optional[str] = None

    class Config:
        from_attributes = True


class DefectEntitySummary(BaseModel):
    id: int
    key: Optional[str] = None
    title: Optional[str] = None
    name: Optional[str] = None
    status: Optional[str] = None


class DefectDetail(BaseModel):
    defect: Defect
    reporter: Optional[DefectUserSummary] = None
    assignee: Optional[DefectUserSummary] = None
    test_case: Optional[DefectEntitySummary] = None
    test_run: Optional[DefectEntitySummary] = None
    requirement: Optional[DefectEntitySummary] = None
    result_links: List[TestResultDefectLink] = Field(default_factory=list)


class TestRunDefectCoverage(BaseModel):
    """Defect-linking rollup for a test run, used for traceability reporting."""
    test_run_id: int
    total_results: int
    failed_or_blocked: int
    linked: int          # failed/blocked results with at least one defect link
    unlinked: int        # failed/blocked results with no defect link
    open_defects: int    # distinct linked defects still in an open-ish status
    retest_needed: int   # results flagged for retest after a defect change


class FlakinessEntry(BaseModel):
    """Cross-run outcome stability for a single test case."""
    runs: int    # number of completed (pass/fail/block) results inspected
    fails: int   # how many of those were failed/blocked
    flaky: bool  # outcomes flip-flop between pass and fail across recent runs


# Enhanced Defect Management Schemas
class DefectManagementBase(BaseModel):
    title: str
    description: Optional[str] = None
    defect_id: str
    status: DefectStatus = DefectStatus.OPEN
    severity: DefectSeverity = DefectSeverity.MEDIUM
    priority: DefectPriority = DefectPriority.MEDIUM
    test_case_id: Optional[int] = None
    test_run_id: Optional[int] = None
    requirement_id: Optional[int] = None
    assigned_to: Optional[int] = None
    tags: Optional[str] = None
    steps_to_reproduce: Optional[str] = None
    expected_result: Optional[str] = None
    actual_result: Optional[str] = None
    environment: Optional[str] = None
    browser_info: Optional[str] = None
    estimated_fix_time: Optional[float] = None
    actual_fix_time: Optional[float] = None
    external_issue_id: Optional[str] = None
    external_issue_url: Optional[str] = None
    external_sync_status: Optional[str] = "not_synced"
    resolution: Optional[str] = None
    root_cause: Optional[str] = None
    fix_version: Optional[str] = None
    found_in_version: Optional[str] = None
    duplicate_of: Optional[int] = None


class DefectManagementCreate(DefectManagementBase):
    pass


class DefectManagementUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    status: Optional[DefectStatus] = None
    severity: Optional[DefectSeverity] = None
    priority: Optional[DefectPriority] = None
    test_case_id: Optional[int] = None
    test_run_id: Optional[int] = None
    requirement_id: Optional[int] = None
    assigned_to: Optional[int] = None
    tags: Optional[str] = None
    steps_to_reproduce: Optional[str] = None
    expected_result: Optional[str] = None
    actual_result: Optional[str] = None
    environment: Optional[str] = None
    browser_info: Optional[str] = None
    estimated_fix_time: Optional[float] = None
    actual_fix_time: Optional[float] = None
    external_issue_id: Optional[str] = None
    external_issue_url: Optional[str] = None
    external_sync_status: Optional[str] = None
    resolution: Optional[str] = None
    root_cause: Optional[str] = None
    fix_version: Optional[str] = None
    found_in_version: Optional[str] = None
    duplicate_of: Optional[int] = None


class User(BaseModel):
    id: int
    username: str
    email: EmailStr
    full_name: Optional[str] = None
    bio: Optional[str] = None
    location: Optional[str] = None
    website: Optional[str] = None
    company: Optional[str] = None
    role: Role = Role.TESTER
    is_active: bool = True
    is_superuser: bool = False
    force_password_change: bool = False
    two_factor_enabled: bool = False
    session_version: int = 0
    created_at: datetime
    updated_at: Optional[datetime] = None

    @field_validator('role', mode='before')
    @classmethod
    def normalize_role_value(cls, value: Any) -> str:
        from ..rbac import role_value
        return role_value(value)

    class Config:
        from_attributes = True


class DefectManagement(DefectManagementBase):
    id: int
    project_id: int
    reported_by: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    reporter: Optional[User] = None
    assignee: Optional[User] = None
    test_case: Optional[Dict[str, Any]] = None
    requirement: Optional[Dict[str, Any]] = None

    class Config:
        from_attributes = True


class DefectManagementDetail(DefectManagement):
    comments: List['DefectComment'] = []
    attachments_files: List['DefectAttachment'] = []
    history: List['DefectHistory'] = []
    duplicate: Optional['DefectManagement'] = None


# Defect Comments Schemas
class DefectCommentBase(BaseModel):
    comment: str
    is_internal: bool = False


class DefectCommentCreate(DefectCommentBase):
    pass


class DefectCommentUpdate(BaseModel):
    comment: Optional[str] = None
    is_internal: Optional[bool] = None


class DefectComment(DefectCommentBase):
    id: int
    defect_id: int
    user_id: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    author: Optional[User] = None

    class Config:
        from_attributes = True


# Defect Attachments Schemas
class DefectAttachmentBase(BaseModel):
    filename: str
    file_size: Optional[int] = None
    mime_type: Optional[str] = None


class DefectAttachment(DefectAttachmentBase):
    id: int
    defect_id: int
    file_path: str
    uploaded_by: int
    uploaded_at: datetime
    uploader: Optional[User] = None

    class Config:
        from_attributes = True


# Defect History Schemas
class DefectHistoryBase(BaseModel):
    field_name: str
    old_value: Optional[str] = None
    new_value: Optional[str] = None
    change_reason: Optional[str] = None


class DefectHistory(DefectHistoryBase):
    id: int
    defect_id: int
    user_id: int
    created_at: datetime
    changed_by: Optional[User] = None

    class Config:
        from_attributes = True


# Issue Tracker Integration Schemas
class IssueTrackerIntegrationBase(BaseModel):
    name: str
    tracker_type: str
    api_url: str
    api_token: Optional[str] = None
    username: Optional[str] = None
    project_key: Optional[str] = None
    sync_direction: str = "bidirectional"
    sync_config: Optional[Dict[str, Any]] = None
    is_active: bool = True


class IssueTrackerIntegrationCreate(IssueTrackerIntegrationBase):
    pass


class IssueTrackerIntegrationUpdate(BaseModel):
    name: Optional[str] = None
    tracker_type: Optional[str] = None
    api_url: Optional[str] = None
    api_token: Optional[str] = None
    username: Optional[str] = None
    project_key: Optional[str] = None
    sync_direction: Optional[str] = None
    sync_config: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class IssueTrackerIntegration(IssueTrackerIntegrationBase):
    id: int
    project_id: int
    last_sync: Optional[datetime] = None
    sync_status: Optional[str] = "not_synced"
    sync_error: Optional[str] = None
    created_by: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    creator: Optional[User] = None

    class Config:
        from_attributes = True


# Defect Sync Schemas
class DefectSyncRequest(BaseModel):
    integration_id: int
    sync_type: str = "manual"  # manual, automatic
    action: str = "sync"  # sync, create, update


class DefectSyncResponse(BaseModel):
    success: bool
    message: str
    external_issue_id: Optional[str] = None
    external_issue_url: Optional[str] = None
    sync_status: Optional[str] = None


# Defect Templates Schemas
class DefectTemplateBase(BaseModel):
    name: str
    description: Optional[str] = None
    template_data: Optional[Dict[str, Any]] = None
    is_active: bool = True


class DefectTemplateCreate(DefectTemplateBase):
    pass


class DefectTemplateUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    template_data: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class DefectTemplate(DefectTemplateBase):
    id: int
    project_id: int
    created_by: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    creator: Optional[User] = None

    class Config:
        from_attributes = True
