import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Loader2, AlertCircle, Printer } from 'lucide-react';
import { analyticsAPI } from '@/lib/api';

/**
 * Public shared-report viewer. Works for both authenticated and anonymous users —
 * the share token in the URL is the only access gate (enforced server-side).
 */
export function SharedReportViewer() {
  const { token } = useParams<{ token: string }>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [report, setReport] = useState<any>(null);

  useEffect(() => {
    if (!token) {
      setError('Missing share token.');
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError(null);
    analyticsAPI
      .getSharedReport(token)
      .then((data) => {
        if (cancelled) return;
        setReport(data);
        setLoading(false);
      })
      .catch((err: any) => {
        if (cancelled) return;
        const status = err?.response?.status;
        if (status === 404) setError('This shared report does not exist or has been deactivated.');
        else if (status === 410) setError('This shared report has expired.');
        else setError('The shared report could not be loaded.');
        setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
        <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 p-6">
        <Card className="max-w-md">
          <CardContent className="flex flex-col items-center py-10 text-center">
            <AlertCircle className="h-10 w-10 text-red-500 mb-3" />
            <p className="text-gray-700 dark:text-gray-200">{error || 'Report unavailable.'}</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  const content = report.report_content || {};
  const kpis = content.kpis || {};
  const summary = content.summary || {};
  const recent = content.recent_activity || {};

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4 print:bg-white print:py-0">
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex items-start justify-between gap-4 print:hidden">
          <div>
            <p className="text-xs uppercase tracking-wide text-gray-500">Shared Report</p>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">{report.title}</h1>
          </div>
          <Button variant="outline" onClick={() => window.print()}>
            <Printer className="h-4 w-4 mr-2" />
            Print / Save as PDF
          </Button>
        </div>

        {/* Header card */}
        <Card>
          <CardHeader>
            <div className="flex items-start justify-between gap-2 flex-wrap">
              <CardTitle className="text-xl">{report.title}</CardTitle>
              <div className="flex flex-wrap gap-2">
                <Badge variant="secondary" className="capitalize">{report.report_type}</Badge>
                <Badge variant="outline" className="capitalize">{report.access_level}</Badge>
                <Badge variant="outline">{report.view_count || 0} views</Badge>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-600 dark:text-gray-300">
              {content.project_name ? (
                <>
                  Project: <span className="font-medium">{content.project_name}</span>
                  {' · '}
                </>
              ) : null}
              Generated by {content.generated_by || 'system'}
              {content.generated_at ? ` on ${new Date(content.generated_at).toLocaleString()}` : ''}
              {report.expires_at ? ` · Expires ${new Date(report.expires_at).toLocaleDateString()}` : ''}
            </p>
          </CardContent>
        </Card>

        {content.kpis && (
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Key Metrics</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                {([
                  ['coverage_percent', 'Coverage', '%'],
                  ['pass_rate_percent', 'Pass Rate', '%'],
                  ['failure_rate_percent', 'Failure Rate', '%'],
                  ['flakiness_percent', 'Flakiness', '%'],
                  ['cycle_time_hours', 'Cycle Time', 'h'],
                  ['defect_density', 'Defect Density', ''],
                ] as [string, string, string][]).map(([key, label, unit]) => (
                  <div key={key} className="rounded-lg border dark:border-gray-700 p-3">
                    <div className="text-xs text-gray-500">{label}</div>
                    <div className="text-2xl font-semibold">
                      {kpis[key] ?? 0}
                      {unit}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {content.summary && (
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Project Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                {([
                  ['total_test_cases', 'Test Cases'],
                  ['total_test_suites', 'Test Suites'],
                  ['total_test_runs', 'Test Runs'],
                  ['total_requirements', 'Requirements'],
                  ['total_defects', 'Defects'],
                ] as [string, string][]).map(([key, label]) => (
                  <div
                    key={key}
                    className="flex justify-between border-b border-gray-100 dark:border-gray-800 py-1.5"
                  >
                    <span className="text-gray-600 dark:text-gray-300">{label}</span>
                    <span className="font-semibold">{summary[key] ?? 0}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {content.recent_activity && (
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Recent Activity</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-3 gap-3 text-center">
                {([
                  ['test_runs_today', 'Runs today'],
                  ['tests_executed', 'Tests executed'],
                  ['defects_found', 'Defects found'],
                ] as [string, string][]).map(([key, label]) => (
                  <div key={key} className="rounded-lg border dark:border-gray-700 p-3">
                    <div className="text-2xl font-semibold">{recent[key] ?? 0}</div>
                    <div className="text-xs text-gray-500">{label}</div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {content.data_available === false && (
          <p className="text-sm text-gray-500 text-center">
            Analytics data was unavailable when this report was generated.
          </p>
        )}
      </div>
    </div>
  );
}
